# Generated by Django 6.0.2 on 2026-02-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=500)),
                ('urun_marka', models.CharField(max_length=500)),
                ('urun_enerji_sinifi', models.CharField(max_length=10)),
                ('urun_fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('urun_resim', models.ImageField(upload_to='urun_resimleri/')),
            ],
        ),
    ]
