# Generated by Django 6.0.2 on 2026-02-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urun',
            new_name='Urunler',
        ),
    ]
