# Generated by Django 6.0.2 on 2026-02-20 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_rename_urun_urunler'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='urun_aciklama',
            field=models.TextField(default='Telefonla ulasinabilir.'),
        ),
        migrations.AddField(
            model_name='urunler',
            name='urun_yayinlanma_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
