# Generated by Django 6.0.2 on 2026-02-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0003_urunler_urun_aciklama_urunler_urun_yayinlanma_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='urun_resim',
            field=models.ImageField(upload_to='media/urun_resimleri/'),
        ),
    ]
