# Generated by Django 6.0.2 on 2026-02-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_alter_urunler_urun_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='urun_resim',
            field=models.ImageField(upload_to='urun_resimleri/'),
        ),
    ]
